FROM node:20-bookworm
WORKDIR /app

RUN apt-get update && apt-get install -y \
    libnspr4 \
    libnss3 \
    libxss1 \
    libdbus-glib-1-2 \
    libatk1.0-0 \
    libatk-bridge2.0-0 \
    libgdk-pixbuf2.0-0 \
    libgtk-3-0 \
    libgbm-dev \
    libasound2 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY package.json package-lock.json ./

RUN npm install

COPY tsconfig.json ./

EXPOSE 3000

CMD ["npm", "run", "start:dev"]